---
version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
  flask:
    image: dmitreykazin/course_attendance_app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  data:
