---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dplmnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: dmitreykazin/course_attendance_app:latest
          ports:
            - name: flask-container
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 10
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: DB_NAME
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: RMT_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RMT_HOST
            - name: RMT_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RMT_USER
            - name: RMT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RMT_PASSWD
