---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  storageClassName: standard
  hostPath:
    path: /data
    type: DirectoryOrCreate
