---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dplmnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
            - name: MYSQL_DATABASE
              value: attendance_app
          ports:
            - name: mysql-container
              containerPort: 3306
          volumeMounts:
            - name: app-data
              mountPath: /var/lib/mysql
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: host-pvc
